### ISSUE TITLE
Méthode : robot.choisir_emotion(texte, liste_emotions) - (chapitre 8)

### ISSUE THREAD

**Issue by mdaadoun** [42Angouleme/pybot#63]
**

> Demander à l'ia de representer l'émotion la plus proche par rapport au texte envoyé et de selectionner une émotion parmi celles présente dans la liste_emotions (qui devrait dans l'idéal représenter un visage correspondant à afficher).
> Retourne l'émotion choisi. ( à combiner avec robot.afficher_image pour afficher le visage)
> voir code essai sur le sujet :
> https://github.com/42Angouleme/pybot/blob/main/pybot/emotion_main.py

**

### Sur le code : https://github.com/42Angouleme/pybot
1. à implémenter (en français sur Robot.py)
2. à commenter dans le code (en français)
### Sur la doc : https://github.com/42Angouleme/42Angouleme.github.io
1. partie tutoriel dans son chapitre à rédiger
2. ajouter méthode dans la référence de la bibliothèque (ref.md)

**Comment by gpoblon** [comment]
closing, merged #89
